"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mongoose_1 = require("mongoose");
var schema = new mongoose_1.Schema({ name: { type: 'String' } });
var Test = (0, mongoose_1.model)('Test', schema);
Test.collection.collectionName;
Test.collection.findOne({});
Test.collection.findOneAndDelete({});
Test.collection.ensureIndex();
Test.collection.findAndModify();
Test.collection.getIndexes();
var coll = mongoose_1.connection.collection('test');
