"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mongoose_1 = require("mongoose");
var tsd_1 = require("tsd");
var preMiddlewareFn = function (next, opts) {
    this.$markValid('name');
    if (opts.session) {
        next();
    }
    else {
        next(new Error('Operation must be in Session.'));
    }
};
var schema = new mongoose_1.Schema({ name: { type: 'String' } });
/* The following tests were generated by test/model.middleware.preposttypes.test.js (with GEN_TSD hardcoded set to true) */
schema.pre('save', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('save', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('save', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('save', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('save', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('save', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('save', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('save', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('save', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('save', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('init', function () {
    (0, tsd_1.expectType)(this);
});
schema.pre('estimatedDocumentCount', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('estimatedDocumentCount', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('estimatedDocumentCount', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('estimatedDocumentCount', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('estimatedDocumentCount', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('estimatedDocumentCount', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('estimatedDocumentCount', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('estimatedDocumentCount', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('estimatedDocumentCount', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('estimatedDocumentCount', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('countDocuments', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('countDocuments', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('countDocuments', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('countDocuments', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('countDocuments', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('countDocuments', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('countDocuments', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('countDocuments', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('countDocuments', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('countDocuments', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteMany', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteMany', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteMany', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteMany', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteMany', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteMany', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteMany', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteMany', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteMany', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteMany', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('distinct', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('distinct', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('distinct', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('distinct', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('distinct', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('distinct', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('distinct', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('distinct', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('distinct', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('distinct', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('find', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('find', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('find', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('find', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('find', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('find', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('find', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('find', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('find', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('find', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOne', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOne', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOne', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOne', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOne', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOne', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOne', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOne', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOne', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOne', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndDelete', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndDelete', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndDelete', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndDelete', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndDelete', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndDelete', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndDelete', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndDelete', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndDelete', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndDelete', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndReplace', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndReplace', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndReplace', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndReplace', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndReplace', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndReplace', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndReplace', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndReplace', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndReplace', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndReplace', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndUpdate', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndUpdate', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndUpdate', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndUpdate', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndUpdate', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndUpdate', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndUpdate', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndUpdate', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('findOneAndUpdate', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('findOneAndUpdate', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('replaceOne', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('replaceOne', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('replaceOne', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('replaceOne', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('replaceOne', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('replaceOne', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('replaceOne', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('replaceOne', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('replaceOne', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('replaceOne', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateMany', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateMany', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateMany', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateMany', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateMany', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateMany', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateMany', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateMany', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateMany', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateMany', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateOne', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateOne', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateOne', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateOne', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateOne', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateOne', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateOne', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateOne', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('updateOne', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('updateOne', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteOne', function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteOne', function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteOne', { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteOne', { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteOne', { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteOne', { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteOne', { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteOne', { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre('deleteOne', { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post('deleteOne', { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany'], { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne'], { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['estimatedDocumentCount', 'countDocuments', 'deleteMany', 'distinct', 'find', 'findOne', 'findOneAndDelete', 'findOneAndReplace', 'findOneAndUpdate', 'replaceOne', 'updateMany', 'save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['save', 'updateOne', 'deleteOne', 'validate'], function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: true, query: true }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
schema.pre(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function () {
    (0, tsd_1.expectType)(this);
});
schema.post(['save', 'updateOne', 'deleteOne', 'validate'], { document: false, query: false }, function (res) {
    (0, tsd_1.expectType)(this);
    (0, tsd_1.expectNotType)(res);
});
/* end of generated tests */
